# Generated by Django 5.2.13 on 2026-04-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('corpo_html', models.TextField(help_text='Você poderá usar HTML aqui para formatar o e-mail')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('enviada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque se o usuário pedir para sair (opt-out)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
