# Generated by Django 5.2.13 on 2026-04-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(default='mail.cra-ma.org.br', max_length=200)),
                ('porta', models.IntegerField(default=465)),
                ('usuario', models.EmailField(help_text='E-mail que fará os envios (ex: contato@cra-ma.org.br)', max_length=254)),
                ('senha', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Configuração SMTP',
                'verbose_name_plural': 'Configuração SMTP',
            },
        ),
    ]
