# Generated by Django 5.2.13 on 2026-04-09 14:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_configuracaosmtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='corpo_html',
            field=tinymce.models.HTMLField(help_text='Use o editor visual para formatar seu e-mail'),
        ),
    ]
