# Generated by Django 5.2.13 on 2026-04-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_campanha_corpo_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosmtp',
            options={'verbose_name': 'Configuração SMTP', 'verbose_name_plural': 'Configurações SMTP'},
        ),
        migrations.AddField(
            model_name='campanha',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, help_text='Selecione contatos específicos ou deixe vazio para enviar a todos os ativos.', to='marketing.contato'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='remetente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketing.configuracaosmtp', verbose_name='Enviar através de'),
        ),
        migrations.AddField(
            model_name='configuracaosmtp',
            name='nome_identificador',
            field=models.CharField(default='Padrao', help_text='Ex: Suporte, Financeiro, Marketing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='categoria',
            field=models.CharField(choices=[('adm', 'Administrador'), ('est', 'Estudante'), ('emp', 'Empresa'), ('ger', 'Geral')], default='ger', max_length=3),
        ),
        migrations.AlterField(
            model_name='configuracaosmtp',
            name='usuario',
            field=models.EmailField(help_text='E-mail que fará os envios', max_length=254),
        ),
    ]
