# Generated by Django 5.2.13 on 2026-04-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_configuracaosmtp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, help_text='Deixe em branco para disparar imediatamente, ou defina uma data para agendar.', null=True),
        ),
    ]
